
// This file has been generated by the GUI designer. Do not modify.
namespace GtkNuGetPackageExplorer
{
	public partial class FileContentEditor
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.ComboBox _fileTypeCombobox;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Mono.TextEditor.TextEditor _textEditor;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GtkNuGetPackageExplorer.FileContentEditor
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w2, 0);
			this.Name = "GtkNuGetPackageExplorer.FileContentEditor";
			// Container child GtkNuGetPackageExplorer.FileContentEditor.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this._fileTypeCombobox = global::Gtk.ComboBox.NewText ();
			this._fileTypeCombobox.Name = "_fileTypeCombobox";
			this.hbox1.Add (this._fileTypeCombobox);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this._fileTypeCombobox]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w5 = new global::Gtk.Viewport ();
			w5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this._textEditor = new global::Mono.TextEditor.TextEditor ();
			this._textEditor.Events = ((global::Gdk.EventMask)(256));
			this._textEditor.Name = "_textEditor";
			this._textEditor.TabsToSpaces = false;
			this._textEditor.SelectionAnchor = 0;
			this._textEditor.HighlightSearchPattern = false;
			this._textEditor.IsCaseSensitive = false;
			this._textEditor.IsWholeWordOnly = false;
			w5.Add (this._textEditor);
			this.GtkScrolledWindow.Add (w5);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w8.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Hide ();
			this._fileTypeCombobox.Changed += new global::System.EventHandler (this.OnFileTypeComboboxChanged);
		}
	}
}
